import http.server
import socketserver
import json
import os
import re

PORT = 5000
DIRECTORY = os.path.dirname(os.path.abspath(__file__))

class StudioHandler(http.server.SimpleHTTPRequestHandler):
    def do_POST(self):
        if self.path == '/save':
            content_length = int(self.headers['Content-Length'])
            post_data = self.rfile.read(content_length)
            data = json.loads(post_data)

            svg_markup = data.get('svgMarkup', '')
            icon_configs = data.get('iconConfigs', {})
            sorted_ids = sorted(icon_configs.keys())
            
            # Paths for root and static
            svg_paths = [
                os.path.join(DIRECTORY, 'libraries', 'icons', 'icons.svg'),
                os.path.join(DIRECTORY, 'static', 'libraries', 'icons', 'icons.svg')
            ]
            list_paths = [
                os.path.join(DIRECTORY, 'libraries', 'icons', 'lista de icones.txt'),
                os.path.join(DIRECTORY, 'static', 'libraries', 'icons', 'lista de icones.txt')
            ]
            js_paths = [
                os.path.join(DIRECTORY, 'libraries', 'grist-config-manager', 'editors', 'config-cards.js'),
                os.path.join(DIRECTORY, 'libraries', 'grist-config-manager', 'editors', 'config-table.js'),
                os.path.join(DIRECTORY, 'static', 'libraries', 'grist-config-manager', 'editors', 'config-cards.js'),
                os.path.join(DIRECTORY, 'static', 'libraries', 'grist-config-manager', 'editors', 'config-table.js')
            ]
            
            # 1. Update icons.svg in both places
            full_svg = f'<!-- libraries/icons/icons.svg - GENERATED BY ICON STUDIO -->\n<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">\n\n{svg_markup}\n</svg>'
            for p in svg_paths:
                if os.path.exists(os.path.dirname(p)):
                    with open(p, 'w', encoding='utf-8') as f:
                        f.write(full_svg)

            # 2. Update apply_icon_config.py (only exists in root)
            config_path = os.path.join(DIRECTORY, 'apply_icon_config.py')
            if os.path.exists(config_path):
                with open(config_path, 'r', encoding='utf-8') as f:
                    lines = f.readlines()
                
                new_lines = []
                skip = False
                for line in lines:
                    if 'config = {' in line:
                        new_lines.append(f'config = {json.dumps(icon_configs, indent=2)}\n')
                        skip = True
                    elif skip and line.strip() == '}':
                        skip = False
                        continue
                    elif not skip:
                        new_lines.append(line)

                with open(config_path, 'w', encoding='utf-8') as f:
                    f.writelines(new_lines)

            # 3. Update lista de icones.txt in both places
            list_content = "Lista de Ícones (IDs)\n\n" + "\n\n".join(sorted_ids)
            for p in list_paths:
                if os.path.exists(os.path.dirname(p)):
                    with open(p, 'w', encoding='utf-8') as f:
                        f.write(list_content)

            # 4. Update JavaScript AVAILABLE_ICONS lists
            js_list_str = json.dumps(sorted_ids, indent=8)
            # Adjust indentation for the final bracket
            js_list_str = js_list_str.replace(']', '        ]') 
            
            for p in js_paths:
                if os.path.exists(p):
                    with open(p, 'r', encoding='utf-8') as f:
                        content = f.read()
                    
                    # Regex to find const AVAILABLE_ICONS = [ ... ];
                    pattern = r'(const AVAILABLE_ICONS = \[).*?(\];)'
                    new_content = re.sub(pattern, f'const AVAILABLE_ICONS = {js_list_str};', content, flags=re.DOTALL)
                    
                    with open(p, 'w', encoding='utf-8') as f:
                        f.write(new_content)
                    print(f"Patched JS list in: {p}")

            self.send_response(200)
            self.send_header('Content-type', 'application/json')
            self.end_headers()
            self.wfile.write(json.dumps({"status": "success"}).encode())
        else:
            self.send_error(404)

    def do_GET(self):
        return http.server.SimpleHTTPRequestHandler.do_GET(self)

os.chdir(DIRECTORY)
with socketserver.TCPServer(("", PORT), StudioHandler) as httpd:
    print(f"Icon Studio Server running at http://localhost:{PORT}/libraries/icons/icon-manager.html")
    print("Press Ctrl+C to stop.")
    httpd.serve_forever()
